// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc692.Demo2015;
    
import edu.wpi.first.wpilibj.*;

import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import java.util.Vector;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController driveTrainleftDriveTalon1;
    public static SpeedController driveTrainleftDriveTalon2;
    public static SpeedController driveTrainrightDriveTalon1;
    public static SpeedController driveTrainrightDriveTalon2;
    public static RobotDrive driveTrainRobotDrive41;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainleftDriveTalon1 = new TalonSRX(0);
        LiveWindow.addActuator("DriveTrain", "leftDriveTalon1", (TalonSRX) driveTrainleftDriveTalon1);
        
        driveTrainleftDriveTalon2 = new Talon(1);
        LiveWindow.addActuator("DriveTrain", "leftDriveTalon2", (Talon) driveTrainleftDriveTalon2);
        
        driveTrainrightDriveTalon1 = new Talon(2);
        LiveWindow.addActuator("DriveTrain", "rightDriveTalon1", (Talon) driveTrainrightDriveTalon1);
        
        driveTrainrightDriveTalon2 = new Talon(3);
        LiveWindow.addActuator("DriveTrain", "rightDriveTalon2", (Talon) driveTrainrightDriveTalon2);
        
        driveTrainRobotDrive41 = new RobotDrive(driveTrainleftDriveTalon1, driveTrainleftDriveTalon2,
              driveTrainrightDriveTalon1, driveTrainrightDriveTalon2);
        
        driveTrainRobotDrive41.setSafetyEnabled(true);
        driveTrainRobotDrive41.setExpiration(0.1);
        driveTrainRobotDrive41.setSensitivity(0.5);
        driveTrainRobotDrive41.setMaxOutput(1.0);


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
